redis supported
r = Apache::Request.new()
r.content_type = "text/html"
a = Apache
host = "127.0.0.1"
port = 6379

a.rputs("> redis connect " + host + ":" + port.to_s + "<br>")
redis = Apache::Redis.new(host, port)

key="hoge"
val="uhohouho"

a.rputs("> redis set " + key + " " + val + "<br>")
redis.set(key, val)

a.rputs("> redis get " + key + "<br>")
Apache.rputs(key + ": " + redis.get(key))

----------------------
> redis connect 127.0.0.1:6379
> redis set hoge uhohouho
> redis get hoge
hoge: uhohouho

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2826,7 +2826,8 @@ done
 
 
 
-for ac_header in string.h unistd.h
+
+for ac_header in string.h unistd.h hiredis/hiredis.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -2971,6 +2972,10 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
+else
+  { { echo "$as_me:$LINENO: error: not found." >&5
+echo "$as_me: error: not found." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 done
